# Generated by Django 3.2.5 on 2021-12-07 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20211208_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_product',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='Shop.order'),
        ),
    ]
