# Generated by Django 3.2.5 on 2021-12-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_alter_product_startscaletime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
